---
output: html_document
---

## Exercise 2.8

__This exercise relates to the "College" data set, which can be found in the file "College.csv". It contains a number of variables for 777 different universities and colleges in the US.__

a. __Use the read.csv() function to read the data into R. Call the loaded data "college". Make sure that you have the directory set to the correct location for the data.__

<!-- enter your solution here -->

b. __Look at the data using the `fix()` function. You should notice that the first column is just the name of each university. We don’t really want R to treat this as data. However, it may be handy to have these names for later.__

<!-- enter your solution here -->

c. __Use the `summary()` function to produce a numerical summary of the variables in the data set.__

<!-- enter your solution here -->

__Use the `pairs()` function to produce a scatterplot matrix of the first ten columns or variables of the data.__

<!-- enter your solution here -->

__Create a new qualitative variable, called "Elite", by binning the "Top10perc" variable. Use the `summary()` function to see how many elite universities there are. Now use the `plot()` function to produce side-by-side boxplots of "Outstate" versus "Elite".__

<!-- enter your solution here -->

__Use the `hist()` function to produce some histograms with numbers of bins for a few of the quantitative variables.__

<!-- enter your solution here -->

__Continue exploring the data, and provide a brief summary of what you discover.__
