---
output: html_document
---

## Exercise 4.12

__This problem involves writing functions.__

a. __Write a function, `Power()`, that prints out the result of raising 2 to the 3rd power. In other words, your function should compute $2^3$ and print out the results.__

<!-- enter your solution here -->

b. __Create a new function, `Power2()`, that allows you to pass any two numbers, "$x$" and "$a$", and prints out the value of "$x^a$".__

<!-- enter your solution here -->

c. __Using the `Power2()` function that you just wrote, compute $10^3$, $81^7$, and $131^3$.__

<!-- enter your solution here -->

d. __Now create a new function, `Power3()`, that actually returns the result "$x^a$" as an R object, rather than simply printing it to the screen. That is, if you store the value "$x^a$" in an object called "result" within your function, then you can simply `return()` this result.__

<!-- enter your solution here -->

e. __Now using the `Power3()` function, create a plot of $f(x)=x \cdot 3$. The x-axis should display a range of integers from 1 to 10, and the y-axis should display $x^2$. Label the axes appropriately, and use an appropriate title for the figure. Consider displaying either the x-axis, the y-axis, or both on the log-scale.__

<!-- enter your solution here -->

f. __Create a function, `PlotPower()`, that allows you to create a plot of "$x$" against "$x^a$" for a fixed "$a$" and for a range of values of "$x$".__

<!-- enter your solution here -->
